name: doctor_app
description: A new Flutter application.

version: 1.0.0+1

environment:
  sdk: ">=2.2.2 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^0.1.2
  date_picker_timeline: ^1.1.3
  flappy_search_bar: ^1.7.2
  autocomplete_textfield: ^1.7.3
  searchable_dropdown: ^1.1.2
  flutter_screenutil: ^1.0.2
  http: ^0.12.0+4
  progress_dialog: ^1.2.2
  shared_preferences: ^0.5.7+2
  outline_material_icons: ^0.1.1
  url_launcher: ^5.4.10


dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

  assets:
   - images/phoneicon.png
   - images/login.png
   - images/applogo.png
   - images/logo.png
   - images/doctor.png
